#!/usr/bin/env bash

# Replace 127.0.0.1 with 127.0.0.2 for localhost
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Append the custom resolution for facebook.com
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
